# 本番起動ポート
server.port=${SERVER_PORT:8080}

# RDS MySQL接続設定
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Google Oauth 本番用
spring.security.oauth2.client.registration.google.client-id==${PROD_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${PROD_GOOGLE_CLIENT_SECRET}

# 本番環境はSQLログは出力しない
spring.jpa.show-sql=false