# アプリケーション名
spring.application.name=todo-app

# 使用するプロファイル
# spring.profiles.active=local

# JPA共通設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Google OAuth共通設定
spring.security.oauth2.client.registration.google.scope=openid,profile,email